# Generated by Django 2.2.10 on 2020-09-09 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_auto_20200830_1401'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-created_date', '-start_time']},
        ),
        migrations.RemoveField(
            model_name='event',
            name='event_id',
        ),
        migrations.AlterField(
            model_name='event',
            name='repeat_mode',
            field=models.CharField(default='once', max_length=20),
        ),
    ]
