# Generated by Django 2.2.10 on 2020-09-09 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_auto_20200909_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
