# Generated by Django 3.0.3 on 2020-09-13 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0009_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-start_time', '-created_date']},
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
